// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAppUpdate() {
  return window['go']['main']['App']['ApplyAppUpdate']();
}

export function Changelog(arg1) {
  return window['go']['main']['App']['Changelog'](arg1);
}

export function Check(arg1) {
  return window['go']['main']['App']['Check'](arg1);
}

export function CheckAppUpdate() {
  return window['go']['main']['App']['CheckAppUpdate']();
}

export function ChooseKey() {
  return window['go']['main']['App']['ChooseKey']();
}

export function ChoosePack() {
  return window['go']['main']['App']['ChoosePack']();
}

export function ChooseServer() {
  return window['go']['main']['App']['ChooseServer']();
}

export function DefaultPack() {
  return window['go']['main']['App']['DefaultPack']();
}

export function KeepWindowSize() {
  return window['go']['main']['App']['KeepWindowSize']();
}

export function LastUpdate() {
  return window['go']['main']['App']['LastUpdate']();
}

export function LogFrontend(arg1) {
  return window['go']['main']['App']['LogFrontend'](arg1);
}

export function OpenLogFolder() {
  return window['go']['main']['App']['OpenLogFolder']();
}

export function OpenReport(arg1) {
  return window['go']['main']['App']['OpenReport'](arg1);
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5);
}

export function SelectPack(arg1) {
  return window['go']['main']['App']['SelectPack'](arg1);
}

export function ServerBehind() {
  return window['go']['main']['App']['ServerBehind']();
}

export function SetConsoleOpen(arg1) {
  return window['go']['main']['App']['SetConsoleOpen'](arg1);
}

export function SetSkipped(arg1, arg2) {
  return window['go']['main']['App']['SetSkipped'](arg1, arg2);
}

export function SetSort(arg1, arg2) {
  return window['go']['main']['App']['SetSort'](arg1, arg2);
}

export function Settings() {
  return window['go']['main']['App']['Settings']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function SyncServer() {
  return window['go']['main']['App']['SyncServer']();
}

export function Undo(arg1) {
  return window['go']['main']['App']['Undo'](arg1);
}

export function Update(arg1, arg2) {
  return window['go']['main']['App']['Update'](arg1, arg2);
}
