// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {resolve} from '../models';
import {main} from '../models';

export function ApplyAppUpdate():Promise<void>;

export function Changelog(arg1:string):Promise<string>;

export function Check(arg1:string):Promise<resolve.Pack>;

export function CheckAppUpdate():Promise<string>;

export function ChooseKey():Promise<string>;

export function ChoosePack():Promise<string>;

export function ChooseServer():Promise<string>;

export function ChooseVersion(arg1:string,arg2:string):Promise<resolve.Mod>;

export function DefaultPack():Promise<string>;

export function KeepWindowSize():Promise<void>;

export function LastUpdate():Promise<main.LastUpdate>;

export function LogFrontend(arg1:string):Promise<void>;

export function OpenLogFolder():Promise<void>;

export function OpenReport(arg1:string):Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function SaveSettings(arg1:string,arg2:string,arg3:boolean,arg4:string,arg5:string):Promise<void>;

export function SelectPack(arg1:string):Promise<void>;

export function ServerBehind():Promise<number>;

export function SetConsoleOpen(arg1:boolean):Promise<void>;

export function SetSkipped(arg1:string,arg2:boolean):Promise<void>;

export function SetSort(arg1:string,arg2:string):Promise<void>;

export function Settings():Promise<main.Settings>;

export function Stop():Promise<void>;

export function SyncServer():Promise<main.ServerSync>;

export function Undo(arg1:Array<string>):Promise<main.UndoResult>;

export function Update(arg1:Array<string>,arg2:boolean):Promise<main.Report>;

export function VersionNotes(arg1:string,arg2:string):Promise<string>;

export function Versions(arg1:string):Promise<Array<resolve.Choice>>;
